# Generated by Django 3.1.1 on 2020-09-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SinglePage',
        ),
    ]
