# Generated by Django 3.1.1 on 2020-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_advancedformsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedformsetting',
            name='from_address',
            field=models.EmailField(default='d@d.com', max_length=254),
        ),
    ]
