# Generated by Django 3.1.1 on 2020-09-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_advancedformsetting_from_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedformsetting',
            name='from_address',
        ),
    ]
