# Generated by Django 3.1.1 on 2020-09-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('homepage', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('project_title', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(choices=[('administration', 'Administration'), ('phd', 'Phd'), ('master', 'Master'), ('undergrad', 'Undergraduate'), ('alumini', 'Alumini')], max_length=50)),
                ('profile_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
